const { defineConfig } = require('cypress')

module.exports = defineConfig({
  chromeWebSecurity: false,
  clientCertificates: [],
  defaultCommandTimeout: 4000,
  downloadsFolder: 'cypress/downloads',
  e2e: {
    experimentalFetchPolyfill: false,
    experimentalInteractiveRunEvents: false,
    experimentalSessionAndOrigin: false,
    experimentalSourceRewriting: false,
    excludeSpecPattern: '*.hot-update.js',
    slowTestThreshold: 10000,
    specPattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: 'cypress/support/e2e.{js,jsx,ts,tsx}',
    setupNodeEvents(on, config) {
      return require('./cypress/plugins/index.js')(on, config)
    },
  },

  execTimeout: 60000,
  fileServerFolder: '',
  fixturesFolder: 'cypress/fixtures',
  hosts: null,
  includeShadowDom: false,
  isInteractive: true,
  keystrokeDelay: 0,
  modifyObstructiveCode: true,  
  numTestsKeptInMemory: 50,
  pageLoadTimeout: 60000,     
  port: null,
  projectId: null,
  redirectionLimit: 20,
  reporter: 'spec',
  reporterOptions: null,
  requestTimeout: 5000,
  resolvedNodePath: null,
  resolvedNodeVersion: null,
  responseTimeout: 30000,
  retries: {
  runMode: 0,
  openMode: 0,
  },
screenshotOnRunFailure: true,
screenshotsFolder: 'cypress/screenshots',
scrollBehavior: 'top',
supportFolder: false,
taskTimeout: 60000,
trashAssetsBeforeRuns: true,
userAgent: null,
video: false,
videoCompression: 32,
videosFolder: 'cypress/videos',
videoUploadOnPasses: true,
viewportHeight: 660,
viewportWidth: 1000,
waitForAnimations: true,
watchForFileChanges: true,
})
